// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagementSys.Data;

#nullable disable

namespace SchoolManagementSys.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20250709093626_jwt fix")]
    partial class jwtfix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolManagementSys.Models.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Parents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St, Ankara",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fffroedasf@fafd.cc",
                            Name = "Ahmet",
                            PasswordHash = "AQAAAAIAAYagAAAAEAoIr7pOPPDCjfwEeIBn+4DakSyPX6CD7C5JS+Qkiu21RW3KBe6Bt6BJP/RmviyBIg==",
                            PhoneNumber = "4512512342134",
                            Surname = "Yılmaz"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Nilüfer, Bursa",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fdasdfsa@12fadfa.daer",
                            Name = "Fatih",
                            PasswordHash = "AQAAAAIAAYagAAAAEOai/eZ7aNIYoupuCLqetIcttf90L21XFenLB8IqrFziV9nU9tkPNTVFXUxFQM7/mw==",
                            PhoneNumber = "451234",
                            Surname = "Arslan"
                        });
                });

            modelBuilder.Entity("SchoolManagementSys.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentityNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2004, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdentityNumber = "12345678901",
                            Name = "Eren",
                            PasswordHash = "AQAAAAIAAYagAAAAEEaGXS08ryTnpoj3oUqiTWPugZEEWIf78g1eejhe05cj4dg+8t6R8DtHwECQknGaQA==",
                            Surname = "Arslan"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2000, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdentityNumber = "12345678901",
                            Name = "Miraç Can",
                            PasswordHash = "AQAAAAIAAYagAAAAEI/kfQKWm1yfGTz8gwWnsoTjF7PGiNg8Mk2M1E/ioHJrNjvAkKytWyCu19qBtpWXLg==",
                            Surname = "Yüksel"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1981, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdentityNumber = "12345678901",
                            Name = "Kürşat",
                            PasswordHash = "AQAAAAIAAYagAAAAEM1bmqK5r31JEQin6fkQDlcF6bqiT4urbkepKizUiRoTXWmLYfEodPYNk4FXSOOBgA==",
                            Surname = "Özel"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1993, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdentityNumber = "12345678901",
                            Name = "Ömer Can",
                            PasswordHash = "AQAAAAIAAYagAAAAEMMEQmmFgtqO4QJEX5WzkxKhEoL7iFE4dfPr2olZOjhidG5gL2uRdtNRYW+Ztd9kuw==",
                            Surname = "Yiğit"
                        });
                });

            modelBuilder.Entity("SchoolManagementSys.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Graduated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1985, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fsadfasfas@aasdfasddas.cascas",
                            Graduated = "Ankara University",
                            Name = "Ali",
                            PasswordHash = "AQAAAAIAAYagAAAAENeRM7xuzloSPSEzLc+ik6LZ60xTCVlTuZRrk2Evp053eneBvFHvqS1nHtSstuejOg==",
                            PhoneNumber = "123456789013234",
                            Subject = "Mathematics",
                            Surname = "Demir"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1984, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fadfas@aasrewdff.aascas",
                            Graduated = "Istanbul University",
                            Name = "Veli",
                            PasswordHash = "AQAAAAIAAYagAAAAEPW55/UpbegLf+QuXY/M7qfIHR2tflYw1iw4QQG2WmPzD+um7Bgv+cRlCC7A7kyVLw==",
                            PhoneNumber = "123451308224",
                            Subject = "Physics",
                            Surname = "Demirci"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
