// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagementSys.Data;

#nullable disable

namespace SchoolManagementSys.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20250708153302_added teacher models")]
    partial class addedteachermodels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolManagementSys.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2004, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Eren",
                            Surname = "Arslan"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2000, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Miraç Can",
                            Surname = "Yüksel"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1981, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kürşat",
                            Surname = "Özel"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1993, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ömer Can",
                            Surname = "Yiğit"
                        });
                });

            modelBuilder.Entity("SchoolManagementSys.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Graduated")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1985, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fsadfasfas@aasdfasddas.cascas",
                            Graduated = "Ankara University",
                            Name = "Ali",
                            PhoneNumber = "123456789013234",
                            Subject = "Mathematics",
                            Surname = "Demir"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1984, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fadfas@aasrewdff.aascas",
                            Graduated = "Istanbul University",
                            Name = "Veli",
                            PhoneNumber = "123451308224",
                            Subject = "Physics",
                            Surname = "Demirci"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
