@rootURL = https://localhost:7294

GET {{rootURL}}/api/students
Accept: application/json

###

GET {{rootURL}}/api/students/5
Accept: application/json

###

POST {{rootURL}}/api/students
Content-Type: application/json
{
  "name": "Omercan",
  "surname": "Yigit",
  "Email": "ocy@kfk.cs",
  "passwordHash": "19930rlfm",
  "dateOfBirth": "1993-04-27T00:00:00"
}

###

PUT {{rootURL}}/api/students/10
Content-Type: application/json
{
  "name": "Kursat",
  "surname": "Ozel",
  "Email": "kozel@cv.net",
  "passwordHash": "1983jfmesmf",
  "dateOfBirth": "1981-06-26T00:00:00"
}

###

DELETE {{rootURL}}/api/students/7

###

GET {{rootURL}}/api/teachers
Accept: application/json

###

GET {{rootURL}}/api/teachers/5
Accept: application/json

###

POST {{rootURL}}/api/teachers
Content-Type: application/json
{
  "name": "Eren",
  "surname": "Arslan",
  "dateOfBirth": "2004-05-31T00:00:00",
  "subject": "Computers",
  "email": "fasfgadg@gfadgfsd.dadaad",
  "passwordHash": "asfsfas43gfja8939842",
  "phoneNumber": "74139416841",
  "graduated": "baun"
}

###

PUT {{rootURL}}/api/teachers/3
Content-Type: application/json
{
  "name": "Tolga",
  "surname": "Benzer",
  "dateOfBirth": "1990-05-30T00:00:00",
  "subject": "Economics",
  "email": "tffasgrfhgv@ffeggd.bmdm",
  "passwordHash": "mjkd93ukoo203",
  "phoneNumber": "3135694329",
  "graduated": "itu"
}

###

DELETE {{rootURL}}/api/teachers/4

###

GET {{rootURL}}/api/parents
Accept: application/json

###

GET {{rootURL}}/api/parents/3
Accept: application/json

###

POST {{rootURL}}/api/parents
Content-Type: application/json
{
  "name": "Eren",
  "surname": "Arslan",
  "dateOfBirth": "2004-05-31T00:00:00",
  "email": "fdafasd@sfdfaa.ccads",
  "passwordHash": "asfsfas43gfja8939842",
  "phoneNumber": "74139416841",
  "address": "Eminonu, Istanbul"
}

###

PUT {{rootURL}}/api/parents/3
Content-Type: application/json

{
  "name": "Fatih",
  "surname": "Arslan",
  "dateOfBirth": "1975-02-03T00:00:00",
  "email": "ddffccfas31@fasdfas.dews",
  "passwordHash": "dasffdasfas",
  "phoneNumber": "321312",
  "address": "Karakoy, Istanbul"
}

###

DELETE {{rootURL}}/api/parents/3

###

POST {{rootURL}}/api/auth/login
Content-Type: application/json
{
  "email": "fdafasd@sfdfaa.ccads",
  "password": "asfsfas43gfja8939842"
}

###

GET {{rootURL}}/api/classes
Accept: application/json

###

GET {{rootURL}}/api/classes/8
Accept: application/json

###

POST {{rootURL}}/api/classes
Content-Type: application/json
{
  "name": "Class 2",
  "teacherId": 5,
  "studentIds": [6, 10, 11]
}

###

PUT {{rootURL}}/api/classes/8
Content-Type: application/json
{
  "name": "Class 2",
  "teacherId": 5,
  "studentIds": [6, 10, 11]
}

###

DELETE {{rootURL}}/api/classes/6

###